title: Ravi Ramchandran
description: Engineering Executive | Enterprise AI Agents, Platform Strategy and Agent Evaluation
author: Ravi Ramchandran
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
url: "https://rramchan12.github.io"
baseurl: ""
